config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api, :defaults => { :format => 'json' } do
    scope '(:apiv)', :module => :v2,
                     :defaults => { :apiv => 'v2' },
                     :apiv => /v1|v2/,
                     :constraints => ApiConstraints.new(:version => 2, :default => true) do
      post 'snapshots/bulk/create_snapshot', :to => 'bulk_snapshots#create'
      constraints(:host_id => /[^\/]+/) do
        resources :hosts, :only => [] do
          constraints(:id => /[^\/]+/) do
            resources :snapshots, except: [:new, :edit] do
              member do
                put :revert
              end
            end
          end
        end
      end
    end
  end

  constraints(host_id: %r{[^/]+}) do
    resources :hosts, only: [] do
      resources :snapshots, module: 'foreman_snapshot_management', only: [:index, :create, :destroy, :update] do
        member do
          put :revert
        end
      end
    end
  end
  resources :snapshots, module: 'foreman_snapshot_management', only: [] do
    collection do
      post :select_multiple_host
      post :create_multiple_host
    end
  end
end

app/helpers/foreman_snapshot_management/hosts_helper.rb
# frozen_string_literal: true

module ForemanSnapshotManagement
  module HostsHelper
    def snapshot_multiple_actions
      return [] unless can_create_snapshots?
      [{ action: [_('Create Snapshot'), select_multiple_host_snapshots_path], priority: 1000 }]
    end

    private

    def can_create_snapshots?
      User.current.can?(:create_snapshots)
    end
  end
end

app/views/hosts/_snapshots_tab.html.erb
<% if @host.compute_resource && @host.compute_resource.capabilities.include?(:snapshots) && authorized_for(:auth_object => @host, :permission => :view_snapshots) %>

<% content_for(:javascripts) do %>
  <%= webpacked_plugins_js_for :foreman_snapshot_management %>
<% end %>
<% content_for(:stylesheets) do %>
  <%= webpacked_plugins_css_for :foreman_snapshot_management %>
<% end %>

<div id='snapshots' class='tab-pane'
  data-ajax-url='<%= host_snapshots_path(host_id: @host)%>'
  data-on-complete='onContentLoad'>
  <%= spinner(_('Loading Snapshots information ...')) %>
</div>
<% end %>